### ISSUE TITLE
API-doc broken

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp-docs#13]

**Comment by djmittens** [comment]
Uhm how do i access the latest docs to learn the library? i was looking at the pdf version but its all messed up, and its missing on the main site as well.
Its so strange, for a project to not have working documentation.  I also tried to generate doxygen docs in the repo itself, and it says its for version 4.1 (from 2018)

![image](https://user-images.githubusercontent.com/4595550/119939560-ea06e800-bf42-11eb-9986-80a51330e60e.png)

![image](https://user-images.githubusercontent.com/4595550/119939590-f4c17d00-bf42-11eb-8539-eb5347d984eb.png)

**Comment by Ryefalk** [comment]
It is still broken, how would you recommend looking at the api some other way?

**Comment by kimkulling** [comment]
Search for the doxygen doc via google. I will try to fix the issue

Ryefalk ***@***.***> schrieb am Do., 8. Juli 2021, 07:49:

**Comment by kimkulling** [comment]
Fixed!
