### ISSUE TITLE
Incorrect logic when checking if the import failed

### ISSUE THREAD

**Issue by ghost** [assimp/assimp-docs#18]
Under https://assimp-docs.readthedocs.io/en/latest/usage/use_the_lib.html

You have 
![image](https://user-images.githubusercontent.com/24993673/162882203-d7b404e6-bdcd-4f34-93fd-00ae320e2957.png)

Has to be if (NULL == scene) or (scene == NULL) otherwise the error is never thrown. Same goes for C++ api

**Comment by kimkulling** [comment]
Thanks a lot for your report. The issue shall be fixed.
