### ISSUE TITLE
Building static library instructions are wrong

### ISSUE THREAD

**Issue by Colins2** [assimp/assimp-docs#20]
The doc currently says this:
Assimp static lib

The Assimp-package can be build as a static library as well. Do do so just set the configuration variable BUILD_SHARED_LIBS to off during the cmake run. For example:

cmake CMakeLists.txt -G "Ninja" -BUILD_SHARED_LIBS=ON

will generate a static library buid by Ninja.

There are a couple of typos, Do do, and buid and ON instead of OFF but the actual instruction is wrong.
Using this generated a directory called "UILD_SHARED_LIBS=OFF" but building from there did not build a static library.
I changed the command to .... -DBUILD_SHARED_LIBS=OFF and simply ran ninja and I got the static library.

I should add I'm building on Linux Mint 21 with gcc 11.2

**Comment by kimkulling** [comment]
Hm, the current master has already all the fixes. Seems that the webside is outdated? I need to check.

**Comment by kimkulling** [comment]
Ok, the old stuff is shown on the webside, but the source is more uptodate. Thanks for the hint.

**Comment by Colins2** [comment]
The build instructions in the readme are not very explicit for Linux which
is why I went to the website documentation.

**Comment by kimkulling** [comment]
I tried my really best to fix this issue in the latest version.
