### ISSUE TITLE
Out-of-date morph info indicating only Collada supported

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp-docs#21]
It seems there is out-of-date information in the docs about morph targets.

In multiple places [here](https://assimp-docs.readthedocs.io/en/v5.1.0/API/API-Documentation.html) e.g.
```
C_STRUCT aiAnimMesh ** mAnimMeshes
    Attachment meshes for this mesh, for vertex-based animation. 
...
Note! Currently only works with Collada loader
```
```
unsigned int mNumAnimMeshes
    The number of attachment meshes.
    Note! Currently only works with Collada loader.
```
but in fact `pAiMesh->mNumAnimMeshes` is populated for gltf 2.0 models containing morph data.

Note: this model can be used to verify:
[AnimatedMorphSphere.glb](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphSphere/glTF-Binary/AnimatedMorphSphere.glb)

**Comment by kimkulling** [comment]
Thanks for the hint. I need to invest some more love into the current documentation. I will take care.

**Comment by kimkulling** [comment]
Shall be fixed now.
