### ISSUE TITLE
Supported .iqm format not mentioned except in code

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp-docs#22]
Going through the bundled test models and only just realized that .iqm ("Inter-Quake Model") format 3D models are supported out-of-the-box by assimp.  Would be great to add a couple of lines to docs/overview web page (slotting `.iqm` between `.ifc` and `.irr`) to increase awareness of support for this format.

Test model: [mrfixit.iqm](https://github.com/assimp/assimp/blob/master/test/models/IQM/mrfixit.iqm)

Refs: 

- http://sauerbraten.org/iqm
- https://github.com/lsalzman/iqm

<img alt="imq_model_format_supported" src="https://user-images.githubusercontent.com/26958898/216231928-7fdd180a-5ca1-4281-b3aa-a003930d2401.png" width=320 />

**Comment by kimkulling** [comment]
Really? Thanks for your hint. So I can integrate this into our CI-testsuite and add the format to our list of supported files.

**Comment by kimkulling** [comment]
Fixed.
