### ISSUE TITLE
Remove references to M3D support

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp-docs#23]
M3D 3D model format support had to be dropped recently (more details can be found here: https://github.com/assimp/assimp/issues/4881)

All references to .m3d/M3D should be removed from documentation pending resolution, would be regrettable if users expect to be able to open .m3d models with assimp and an implementation has to refuse the request...

**Comment by kimkulling** [comment]
Thanks for the report. In the current version this one is already fixed.
